[server.pv.addon.broadcast]
broadcasting_wide = "向 %s 范围广播"
broadcasting_specific = "向 %s 广播"

[server.pv.addon.broadcast.command]
usage = "用法：/vbroadcastproxy <server|proxy> <服务器名称>"

server_usage = "用法：/vbroadcastproxy server <服务器名称>"
server_set = "设置广播为向 %s 广播的服务器模式"

proxy_set = "设置广播为代理模式"

[client.pv.activation]
broadcast = "广播"
