name: Publish Release

on:
  push:
    branches:
      - release

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v6
    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: |
          8
          16
          17

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5

    - name: Build with Gradle
      run: ./gradlew build

    - name: Publish to Modrinth/CurseForge
      uses: apehum/mc-publish@v1.2
      with:
        modrinth-id: ZI9h3Y7k
        modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
        changelog-file: changelog.md

        curseforge-id: 1412699
        curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

        loaders: |
          fabric
          forge
          neoforge
          paper
          spigot
          velocity
          bungeecord
        game-versions: |
          1.16.5
          1.17.1
          1.18.2
          >=1.19.2
        
    - name: Publish to GitHub
      uses: Apehum/mc-publish@v1.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        github-generate-changelog: false
        changelog-file: changelog.md
